"""From-scratch bot office-hook wiring (docs/OFFICE_HOOK_FROM_SCRATCH_BOTS.md) —
proves the gap described there is closed: a bot generated by
GENERATE_SYSTEM_PROMPT (no `# TEMPLATE:` marker, no templates/*.py module)
still gets router/config/office-hook wiring through runtime/registry.py's
build_entry(), via services.claude_service.append_from_scratch_registry_wiring
appending config_from_bot_row/ConfigMiddleware/on_office_event to the
generated file and build_entry() importing that file DIRECTLY by path
(_load_generated_bot_module_async) when template_id is None.

Three layers, same split as tests/test_office_events_registry_wiring.py
(the template-based equivalent this mirrors):
1. append_from_scratch_registry_wiring in isolation — the text injection.
2. build_entry() with template_id=None + file_path — the new resolution path.
3. Full e2e: from-scratch bot file on disk -> build_entry() -> office event ->
   generic hook fires and writes to the bot's OWN db_path.

Run with: python -m pytest tests/test_from_scratch_office_hook.py
"""
from __future__ import annotations

import sqlite3
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

import db.database as db_module
import runtime.registry as reg
import services.claude_service as claude_service

FAKE_TOKEN = "123456789:AAHfakeTokenButShapedRight1234567890"

# Shaped exactly like GENERATE_SYSTEM_PROMPT's mandatory conventions:
# BOT_NAME/DB_PATH module globals, init_db(db_path) taking the path as a
# parameter, router at module level, asyncio.run(main()) entry point.
_FROM_SCRATCH_BOT_SOURCE = '''
import os
import asyncio
import aiosqlite
from pathlib import Path
from aiogram import Bot, Dispatcher, Router
from aiogram.filters import CommandStart
from aiogram.types import Message
from aiogram.fsm.storage.memory import MemoryStorage

BOT_NAME = Path(__file__).stem
DB_PATH = os.path.join(os.getenv("DATA_DIR", "./data"), f"{BOT_NAME}_data.db")
router = Router()


async def init_db(db_path: str) -> None:
    async with aiosqlite.connect(db_path) as db:
        await db.execute(
            "CREATE TABLE IF NOT EXISTS orders (id INTEGER PRIMARY KEY AUTOINCREMENT, item TEXT)"
        )
        await db.commit()


@router.message(CommandStart())
async def cmd_start(message: Message):
    await message.answer("hello")


async def main():
    bot = Bot(token=os.getenv("BOT_TOKEN"))
    dp = Dispatcher(storage=MemoryStorage())
    dp.include_router(router)
    await init_db(DB_PATH)
    await dp.start_polling(bot)


if __name__ == "__main__":
    asyncio.run(main())
'''


class AppendFromScratchRegistryWiring(unittest.TestCase):
    """Layer 1 — the text-injection step in isolation, no registry involved."""

    def test_injects_all_three_exports_and_stays_valid_python(self):
        import ast

        wired = claude_service.append_from_scratch_registry_wiring(_FROM_SCRATCH_BOT_SOURCE)
        ast.parse(wired)  # raises on any syntax error
        self.assertIn("def config_from_bot_row(", wired)
        self.assertIn("class ConfigMiddleware(", wired)
        self.assertIn("async def on_office_event(", wired)
        # Injected before the entry point, not after (module must still be
        # importable — code after asyncio.run(main()) never executes at
        # import time makes no difference here, but keeping it before is
        # what the implementation promises).
        self.assertLess(wired.index("def config_from_bot_row("), wired.index('if __name__ =='))

    def test_is_idempotent_does_not_double_append(self):
        wired_once = claude_service.append_from_scratch_registry_wiring(_FROM_SCRATCH_BOT_SOURCE)
        wired_twice = claude_service.append_from_scratch_registry_wiring(wired_once)
        self.assertEqual(wired_once.count("def config_from_bot_row("), 1)
        self.assertEqual(wired_twice.count("def config_from_bot_row("), 1)

    def test_stateless_bot_with_no_init_db_gets_a_noop_fallback(self):
        import ast

        stateless = '''
import os
import asyncio
from aiogram import Bot, Dispatcher, Router
from aiogram.fsm.storage.memory import MemoryStorage

router = Router()


async def main():
    bot = Bot(token=os.getenv("BOT_TOKEN"))
    dp = Dispatcher(storage=MemoryStorage())
    dp.include_router(router)
    await dp.start_polling(bot)


if __name__ == "__main__":
    asyncio.run(main())
'''
        wired = claude_service.append_from_scratch_registry_wiring(stateless)
        ast.parse(wired)
        self.assertIn("async def init_db(db_path: str) -> None:", wired)

    def test_no_entry_point_is_a_safe_noop(self):
        broken = "x = 1\n"
        self.assertEqual(claude_service.append_from_scratch_registry_wiring(broken), broken)


class BuildEntryResolvesFromScratchBotsByFilePath(unittest.IsolatedAsyncioTestCase):
    """Layer 2 + 3 — build_entry() with template_id=None + file_path, through
    to a live office event reaching the generic hook."""

    async def asyncSetUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.tmp_dir = Path(self._tmp.name)
        self._data_dir = self.tmp_dir / "data"
        self._data_dir.mkdir()

        # Same DB isolation as test_office_events_registry_wiring.py — build_entry()
        # calls _load_and_include_features(), which reads db.database.DB_PATH.
        self._config_patcher = patch("config.DATA_DIR", self._data_dir)
        self._config_patcher.start()
        self._db_path_patcher = patch.object(db_module, "DB_PATH", self._data_dir / "bots.db")
        self._db_path_patcher.start()
        await db_module.init_db()

        # The from-scratch bot's OWN DB_PATH global is computed at import time
        # from os.getenv("DATA_DIR", ...) directly (GENERATE_SYSTEM_PROMPT's
        # convention, not config.DATA_DIR) — in prod these are the same source
        # (config.py's DATA_DIR is itself os.getenv("DATA_DIR", ...)), so the
        # env var must be patched too for the bot module to land its DB in
        # the same temp dir the test/registry code uses.
        self._env_patcher = patch.dict("os.environ", {"DATA_DIR": str(self._data_dir)})
        self._env_patcher.start()

        wired_source = claude_service.append_from_scratch_registry_wiring(_FROM_SCRATCH_BOT_SOURCE)
        self.bot_file = self._data_dir / "generated_bots" / "my_from_scratch_bot.py"
        self.bot_file.parent.mkdir(parents=True, exist_ok=True)
        self.bot_file.write_text(wired_source, encoding="utf-8")

    async def asyncTearDown(self):
        self._env_patcher.stop()
        self._db_path_patcher.stop()
        self._config_patcher.stop()
        self._tmp.cleanup()

    async def test_router_and_office_hook_are_wired_with_no_template_id(self):
        entry = await reg.build_entry(
            9201,
            FAKE_TOKEN,
            None,  # no # TEMPLATE: marker — the from-scratch case
            {"bot_id": 9201, "name": "my_from_scratch_bot"},
            file_path=str(self.bot_file),
        )
        try:
            # Router resolved and mounted (dp.resolve_used_update_types is a
            # cheap way to prove at least one handler is registered without
            # dispatching a real update).
            self.assertTrue(len(entry.dispatcher.sub_routers) > 0 or entry.dispatcher.observers)
            self.assertIn("on_office_event", entry.config)
            self.assertEqual(entry.config.get("db_path"), str(self._data_dir / "my_from_scratch_bot_data.db"))
        finally:
            await entry.bot.session.close()

    async def test_office_event_reaches_the_generic_hook_and_writes_a_note(self):
        from features.office_events import OfficeEvent, OrderCreatedEvent

        entry = await reg.build_entry(
            9202,
            FAKE_TOKEN,
            None,
            {"bot_id": 9202, "name": "my_from_scratch_bot_2"},
            file_path=str(self.bot_file),
        )
        try:
            hook = entry.config["on_office_event"]
            event = OfficeEvent(
                event_type="order.created",
                source_bot_id=1,
                payload=OrderCreatedEvent(order_id=1, amount=100, currency="RUB", customer_chat_id=555),
            )
            await hook(event)

            # db_path comes from the bot file's OWN BOT_NAME (Path(__file__).stem),
            # not the "name" field passed into build_entry()'s config — see
            # config_from_bot_row in the appended wiring.
            db_path = self._data_dir / "my_from_scratch_bot_data.db"
            conn = sqlite3.connect(str(db_path))
            rows = conn.execute("SELECT source_bot_id, event_type, note FROM office_notes").fetchall()
            conn.close()
            self.assertEqual(len(rows), 1)
            self.assertEqual(rows[0][0], 1)
            self.assertEqual(rows[0][1], "order.created")
        finally:
            await entry.bot.session.close()

    async def test_bots_own_table_from_init_db_actually_exists(self):
        # init_db(config.db_path) ran during build_entry() (via
        # _build_generic_middleware, same as any templates/*.py module) —
        # the bot's own `orders` table must exist even though this bot was
        # never run standalone via its own asyncio.run(main()).
        entry = await reg.build_entry(
            9203,
            FAKE_TOKEN,
            None,
            {"bot_id": 9203, "name": "my_from_scratch_bot_3"},
            file_path=str(self.bot_file),
        )
        try:
            db_path = self._data_dir / "my_from_scratch_bot_data.db"
            conn = sqlite3.connect(str(db_path))
            tables = {
                row[0] for row in conn.execute("SELECT name FROM sqlite_master WHERE type='table'").fetchall()
            }
            conn.close()
            self.assertIn("orders", tables)
        finally:
            await entry.bot.session.close()

    async def test_broken_from_scratch_file_falls_back_to_generic_middleware_no_router(self):
        broken_file = self._data_dir / "generated_bots" / "broken_bot.py"
        broken_file.write_text("this is not ) valid python(((", encoding="utf-8")
        entry = await reg.build_entry(
            9204,
            FAKE_TOKEN,
            None,
            {"bot_id": 9204, "name": "broken_bot"},
            file_path=str(broken_file),
        )
        try:
            self.assertNotIn("on_office_event", entry.config)
        finally:
            await entry.bot.session.close()


if __name__ == "__main__":
    unittest.main()
