"""From-scratch bot voice-intake/cashflow-ledger wiring (docs/
VOICE_CASHFLOW_FROM_SCRATCH_DESIGN.md) — proves a bot generated by
GENERATE_SYSTEM_PROMPT (no `# TEMPLATE:` marker, no templates/*.py module)
can get a working data-driven VoiceSchema and a cashflow_entries table
purely through the bot_features opt-in mechanism + a generated
bot_voice_cashflow_config row, with NO hand-written Python in the bot's own
file — mirrors tests/test_from_scratch_office_hook.py's structure (same
from-scratch fixture shape, same DB isolation pattern), for the
voice_intake/cashflow_ledger feature path instead of the office-hook path.

Two layers:
1. runtime/registry.py's _register_voice_intake_schema in isolation — the
   config-fetch + re-validate + register_data_driven_schema call.
2. Full e2e: from-scratch bot file on disk, with voice_intake/cashflow_ledger
   enabled in bot_features and a bot_voice_cashflow_config row -> build_entry()
   -> a live voice message reaches the generic data-driven save path and
   writes into the bot's OWN db_path; cashflow_ledger's init_db creates
   cashflow_entries in the same db_path.

Run with: python -m pytest tests/test_from_scratch_voice_cashflow_wiring.py
"""
from __future__ import annotations

import sqlite3
import tempfile
import unittest
from pathlib import Path
from unittest.mock import AsyncMock, patch

import db.database as db_module
import runtime.registry as reg
import services.claude_service as claude_service

FAKE_TOKEN = "123456789:AAHfakeTokenButShapedRight1234567890"

# Same conventions as test_from_scratch_office_hook.py's fixture: BOT_NAME/
# DB_PATH module globals, init_db(db_path) taking the path as a parameter,
# router at module level, asyncio.run(main()) entry point — plus its own
# `warehouses`/`items` tables, matching the voice_cashflow_config below.
_FROM_SCRATCH_BOT_SOURCE = '''
import os
import asyncio
import aiosqlite
from pathlib import Path
from aiogram import Bot, Dispatcher, Router
from aiogram.filters import CommandStart
from aiogram.types import Message
from aiogram.fsm.storage.memory import MemoryStorage

BOT_NAME = Path(__file__).stem
DB_PATH = os.path.join(os.getenv("DATA_DIR", "./data"), f"{BOT_NAME}_data.db")
router = Router()


async def init_db(db_path: str) -> None:
    async with aiosqlite.connect(db_path) as db:
        await db.execute(
            "CREATE TABLE IF NOT EXISTS warehouses (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT, user_id TEXT)"
        )
        await db.execute(
            "CREATE TABLE IF NOT EXISTS items (id INTEGER PRIMARY KEY AUTOINCREMENT, warehouse_id INTEGER, title TEXT, quantity INTEGER)"
        )
        await db.commit()


@router.message(CommandStart())
async def cmd_start(message: Message):
    await message.answer("hello")


async def main():
    bot = Bot(token=os.getenv("BOT_TOKEN"))
    dp = Dispatcher(storage=MemoryStorage())
    dp.include_router(router)
    await init_db(DB_PATH)
    await dp.start_polling(bot)


if __name__ == "__main__":
    asyncio.run(main())
'''

_VOICE_CASHFLOW_CONFIG = {
    "voice_intake": {
        "context_table": "warehouses",
        "context_column": "id",
        "record_types": [
            {
                "key": "item", "label": "Item", "icon": "📦",
                "prompt_desc": "title, quantity",
                "table": "items",
                "context_column": "warehouse_id",
                "fields": [
                    {"name": "title", "label": "Title", "column": "title"},
                    {"name": "quantity", "label": "Quantity", "column": "quantity"},
                ],
            },
        ],
    },
    "cashflow_ledger": True,
}


class FromScratchVoiceCashflowWiring(unittest.IsolatedAsyncioTestCase):
    async def asyncSetUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.tmp_dir = Path(self._tmp.name)
        self._data_dir = self.tmp_dir / "data"
        self._data_dir.mkdir()

        self._config_patcher = patch("config.DATA_DIR", self._data_dir)
        self._config_patcher.start()
        self._db_path_patcher = patch.object(db_module, "DB_PATH", self._data_dir / "bots.db")
        self._db_path_patcher.start()
        await db_module.init_db()

        self._env_patcher = patch.dict("os.environ", {"DATA_DIR": str(self._data_dir)})
        self._env_patcher.start()

        wired_source = claude_service.append_from_scratch_registry_wiring(_FROM_SCRATCH_BOT_SOURCE)
        self.bot_file = self._data_dir / "generated_bots" / "my_inventory_bot.py"
        self.bot_file.parent.mkdir(parents=True, exist_ok=True)
        self.bot_file.write_text(wired_source, encoding="utf-8")

        self.db_path = self._data_dir / "my_inventory_bot_data.db"

    async def asyncTearDown(self):
        self._env_patcher.stop()
        self._db_path_patcher.stop()
        self._config_patcher.stop()
        self._tmp.cleanup()
        import features.voice_intake as voice_intake

        voice_intake._schemas.clear()

    async def _create_bot_row(self, bot_id: int, name: str) -> None:
        await db_module.create_bot_record_with_admins(
            name=name, description="", token=FAKE_TOKEN, file_path=str(self.bot_file),
            admin_ids=["1"], username=None,
        )
        # create_bot_record_with_admins auto-assigns bot_id; force it to the
        # id this test wants so bot_features/bot_voice_cashflow_config rows
        # (keyed by the SAME bot_id build_entry() will use) line up.
        import aiosqlite

        async with aiosqlite.connect(db_module.DB_PATH) as db:
            await db.execute("UPDATE bots SET id = ? WHERE name = ?", (bot_id, name))
            await db.commit()

    async def test_register_voice_intake_schema_wires_a_working_schema(self):
        await self._create_bot_row(9301, "inv_bot_1")
        await db_module.enable_bot_feature(9301, "voice_intake")
        await db_module.enable_bot_feature(9301, "cashflow_ledger")
        await db_module.set_bot_voice_cashflow_config(9301, _VOICE_CASHFLOW_CONFIG)

        entry = await reg.build_entry(
            9301, FAKE_TOKEN, None,
            {"bot_id": 9301, "name": "inv_bot_1"},
            file_path=str(self.bot_file),
        )
        try:
            import features.voice_intake as voice_intake

            schema = voice_intake._schemas.get(9301)
            self.assertIsNotNone(schema)
            self.assertEqual(schema.record_types[0].table, "items")
            self.assertEqual(schema.context_table, "warehouses")
        finally:
            await entry.bot.session.close()

    async def test_cashflow_ledger_table_created_via_generic_init_db_pickup(self):
        await self._create_bot_row(9302, "inv_bot_2")
        await db_module.enable_bot_feature(9302, "cashflow_ledger")

        entry = await reg.build_entry(
            9302, FAKE_TOKEN, None,
            {"bot_id": 9302, "name": "inv_bot_2"},
            file_path=str(self.bot_file),
        )
        try:
            conn = sqlite3.connect(str(self.db_path))
            tables = {
                row[0] for row in conn.execute("SELECT name FROM sqlite_master WHERE type='table'").fetchall()
            }
            conn.close()
            self.assertIn("cashflow_entries", tables)
        finally:
            await entry.bot.session.close()

    async def test_e2e_voice_message_saves_via_generic_data_driven_path(self):
        await self._create_bot_row(9303, "inv_bot_3")
        await db_module.enable_bot_feature(9303, "voice_intake")
        await db_module.set_bot_voice_cashflow_config(9303, _VOICE_CASHFLOW_CONFIG)

        entry = await reg.build_entry(
            9303, FAKE_TOKEN, None,
            {"bot_id": 9303, "name": "inv_bot_3"},
            file_path=str(self.bot_file),
        )
        try:
            import aiosqlite

            async with aiosqlite.connect(str(self.db_path)) as db:
                cur = await db.execute("INSERT INTO warehouses(name, user_id) VALUES('Main', '555')")
                await db.commit()
                warehouse_id = cur.lastrowid

            import features.voice_intake as voice_intake

            with patch.object(voice_intake, "_transcribe_voice", new=AsyncMock(return_value="Ten hammers")), \
                 patch.object(voice_intake, "_parse_with_claude", new=AsyncMock(
                     return_value={"type": "item", "data": {"title": "Hammer", "quantity": 10}, "confidence": 0.9})):
                voice_update = {
                    "update_id": 1,
                    "message": {
                        "message_id": 1, "date": 1700000000,
                        "chat": {"id": 555, "type": "private"},
                        "from": {"id": 555, "is_bot": False, "first_name": "Test"},
                        "voice": {"file_id": "voice-1", "file_unique_id": "u1", "duration": 3},
                    },
                }
                callback_update = {
                    "update_id": 2,
                    "callback_query": {
                        "id": "2",
                        "from": {"id": 555, "is_bot": False, "first_name": "Test"},
                        "message": {
                            "message_id": 1, "date": 1700000000,
                            "chat": {"id": 555, "type": "private"}, "text": "placeholder",
                        },
                        "chat_instance": "1", "data": "vs_save",
                    },
                }
                with patch.object(entry.bot.__class__, "__call__", new=AsyncMock(return_value=AsyncMock())):
                    await entry.dispatcher.feed_webhook_update(entry.bot, voice_update)
                    await entry.dispatcher.feed_webhook_update(entry.bot, callback_update)

            conn = sqlite3.connect(str(self.db_path))
            rows = conn.execute("SELECT warehouse_id, title, quantity FROM items").fetchall()
            conn.close()
            self.assertEqual(rows, [(warehouse_id, "Hammer", 10)])
        finally:
            await entry.bot.session.close()

    async def test_no_config_row_leaves_feature_router_loaded_but_no_schema(self):
        await self._create_bot_row(9304, "inv_bot_4")
        await db_module.enable_bot_feature(9304, "voice_intake")
        # No set_bot_voice_cashflow_config call — config is absent entirely.

        entry = await reg.build_entry(
            9304, FAKE_TOKEN, None,
            {"bot_id": 9304, "name": "inv_bot_4"},
            file_path=str(self.bot_file),
        )
        try:
            import features.voice_intake as voice_intake

            self.assertIsNone(voice_intake._schemas.get(9304))
        finally:
            await entry.bot.session.close()

    async def test_stale_config_referencing_missing_table_is_skipped(self):
        await self._create_bot_row(9305, "inv_bot_5")
        await db_module.enable_bot_feature(9305, "voice_intake")
        stale_config = {
            "voice_intake": {
                "context_table": "warehouses", "context_column": "id",
                "record_types": [{
                    "key": "ghost", "label": "Ghost", "icon": "👻",
                    "prompt_desc": "x",
                    "table": "table_that_was_removed",
                    "context_column": None,
                    "fields": [{"name": "x", "label": "X", "column": "x"}],
                }],
            },
            "cashflow_ledger": False,
        }
        await db_module.set_bot_voice_cashflow_config(9305, stale_config)

        entry = await reg.build_entry(
            9305, FAKE_TOKEN, None,
            {"bot_id": 9305, "name": "inv_bot_5"},
            file_path=str(self.bot_file),
        )
        try:
            import features.voice_intake as voice_intake

            self.assertIsNone(voice_intake._schemas.get(9305))
        finally:
            await entry.bot.session.close()


if __name__ == "__main__":
    unittest.main()
