/* Normalizes the dynamic schema fetched from GET /api/{bot_id}/schema (see
   runtime/miniapp_api.py's schema_handler) into the same per-field-kind,
   per-screen-list shape the screens (ListScreen/DetailScreen/
   CreateFormScreen) already render. Replaces the old static resources.ts —
   see Phase 2 design doc §2.4: display metadata now comes from the backend's
   miniapp_config (hand-authored in templates/*.py or generated by the Haiku
   step in services/claude_service.py) instead of being duplicated by hand
   here for every bot.

   Falls back to sane defaults for any field missing display metadata (older
   configs stored before this schema existed still render, just with
   less-polished labels/ordering — degrade gracefully, never blank-screen). */

import type { SchemaField, SchemaResource } from './api'

export interface FieldDisplay {
  name: string
  label: string
  kind: 'text' | 'number' | 'date' | 'status'
}

export interface ResourceDisplay {
  name: string
  title: string
  titleField: string
  listFields: FieldDisplay[]
  detailFields: FieldDisplay[]
  createFields: FieldDisplay[]
}

function humanizeFieldName(name: string): string {
  return name.replace(/_/g, ' ').replace(/^./, (c) => c.toUpperCase())
}

function normalizeField(field: SchemaField): FieldDisplay {
  return {
    name: field.name,
    label: field.label ?? humanizeFieldName(field.name),
    kind: field.kind ?? 'text',
  }
}

export function normalizeResource(resource: SchemaResource): ResourceDisplay {
  const fields = resource.fields.map(normalizeField)
  const byFlag = (flag: 'list' | 'detail' | 'create', defaultValue: boolean) =>
    resource.fields.filter((f) => (f[flag] ?? defaultValue) === true).map(normalizeField)

  return {
    name: resource.name,
    title: resource.title ?? resource.name,
    titleField: resource.titleField ?? fields[0]?.name ?? 'id',
    // Old configs (no list/detail/create flags) fall back to "show
    // everything in detail, nothing extra in the list chips, everything
    // creatable in the form" — the closest approximation to the
    // pre-Phase-2 static resources.ts behavior without guessing which 1-3
    // fields deserve list prominence.
    listFields: byFlag('list', false),
    detailFields: byFlag('detail', true),
    createFields: resource.fields
      .filter((f) => (f.create ?? f.creatable ?? true) === true)
      .map(normalizeField),
  }
}

export function normalizeResources(resources: SchemaResource[]): Record<string, ResourceDisplay> {
  const out: Record<string, ResourceDisplay> = {}
  for (const resource of resources) {
    out[resource.name] = normalizeResource(resource)
  }
  return out
}

const PAID_STATUSES = new Set(['paid', 'active', 'confirmed'])

/* Тон статуса для варианта I: в эталоне-мокапе статусы цветные
   (planning — янтарный, confirmed — зелёный, завершён — медный,
   draft — серый), а прежний statusTone() различал только «успех» и
   «нейтрально», из-за чего всё сводилось к серому.

   Словарь намеренно двуязычный и по подстроке: статусы приходят из
   miniapp_config каждого бота и не унифицированы (paid/оплачен/completed…).
   Порядок проверок важен — «отменён» должен победить «завершён», а
   «завершён» — «активен». Неизвестный статус остаётся нейтральным, а не
   красится наугад. */
export type StatusTone = 'ok' | 'warn' | 'done' | 'danger' | 'neutral'

const TONE_RULES: Array<[RegExp, StatusTone]> = [
  [/cancel|reject|fail|overdue|declin|отмен|отклон|просроч|провал/i, 'danger'],
  [/done|complete|closed|finish|archiv|завершен|завершён|закрыт|выполн|готов/i, 'done'],
  [/paid|active|confirm|approv|success|оплач|подтвержд|актив|принят/i, 'ok'],
  [/plan|pending|wait|new|progress|process|hold|book|планир|ожид|в работе|нов|бронь/i, 'warn'],
]

export function statusToneRich(status: unknown): StatusTone {
  if (typeof status !== 'string' || status.trim() === '') return 'neutral'
  for (const [re, tone] of TONE_RULES) {
    if (re.test(status)) return tone
  }
  return 'neutral'
}

export function statusTone(status: unknown): 'success' | 'neutral' {
  return typeof status === 'string' && PAID_STATUSES.has(status) ? 'success' : 'neutral'
}
