/* Normalizes the dynamic schema fetched from GET /api/{bot_id}/schema (see
   runtime/miniapp_api.py's schema_handler) into the same per-field-kind,
   per-screen-list shape the screens (ListScreen/DetailScreen/
   CreateFormScreen) already render. Replaces the old static resources.ts —
   see Phase 2 design doc §2.4: display metadata now comes from the backend's
   miniapp_config (hand-authored in templates/*.py or generated by the Haiku
   step in services/claude_service.py) instead of being duplicated by hand
   here for every bot.

   Falls back to sane defaults for any field missing display metadata (older
   configs stored before this schema existed still render, just with
   less-polished labels/ordering — degrade gracefully, never blank-screen). */

import type { SchemaChild, SchemaField, SchemaRef, SchemaResource } from './api'

export interface FieldDisplay {
  name: string
  label: string
  kind: 'text' | 'number' | 'date' | 'status' | 'link' | 'file' | 'username'
  ref?: SchemaRef
}

export interface ResourceDisplay {
  name: string
  title: string
  titleField: string
  canCreate: boolean
  tableView: boolean
  children: SchemaChild[]
  listFields: FieldDisplay[]
  detailFields: FieldDisplay[]
  createFields: FieldDisplay[]
}

// A URL-bearing value should be tappable wherever it appears, even when the
// config never labelled the field as a link — most templates predate the
// 'link' kind and just store a maps/booking/site URL in a plain text column.
const URL_RE = /^https?:\/\/\S+$/i

export function isLinkValue(field: FieldDisplay, value: unknown): boolean {
  return field.kind === 'link' || (typeof value === 'string' && URL_RE.test(value.trim()))
}

function humanizeFieldName(name: string): string {
  return name.replace(/_/g, ' ').replace(/^./, (c) => c.toUpperCase())
}

function normalizeField(field: SchemaField): FieldDisplay {
  return {
    name: field.name,
    label: field.label ?? humanizeFieldName(field.name),
    kind: field.kind ?? 'text',
    ref: field.ref,
  }
}

export function normalizeResource(resource: SchemaResource): ResourceDisplay {
  const fields = resource.fields.map(normalizeField)
  const byFlag = (flag: 'list' | 'detail' | 'create', defaultValue: boolean) =>
    resource.fields.filter((f) => (f[flag] ?? defaultValue) === true).map(normalizeField)

  return {
    name: resource.name,
    title: resource.title ?? resource.name,
    titleField: resource.titleField ?? fields[0]?.name ?? 'id',
    // Defaults to false, not to `resource.creatable`: a config served by a
    // backend that doesn't send canCreate can't promise the POST would
    // succeed, and offering a form that 403s is exactly the failure this
    // flag exists to prevent.
    canCreate: resource.canCreate === true,
    tableView: resource.tableView === true,
    children: resource.children ?? [],
    // Old configs (no list/detail/create flags) fall back to "show
    // everything in detail, nothing extra in the list chips, everything
    // creatable in the form" — the closest approximation to the
    // pre-Phase-2 static resources.ts behavior without guessing which 1-3
    // fields deserve list prominence.
    listFields: byFlag('list', false),
    detailFields: byFlag('detail', true),
    createFields: resource.fields
      .filter((f) => (f.create ?? f.creatable ?? true) === true)
      .map(normalizeField),
  }
}

export function normalizeResources(resources: SchemaResource[]): Record<string, ResourceDisplay> {
  const out: Record<string, ResourceDisplay> = {}
  for (const resource of resources) {
    out[resource.name] = normalizeResource(resource)
  }
  return out
}

const PAID_STATUSES = new Set(['paid', 'active', 'confirmed'])

export function statusTone(status: unknown): 'success' | 'neutral' {
  return typeof status === 'string' && PAID_STATUSES.has(status) ? 'success' : 'neutral'
}
