# FEATURE: word_export
# COMPATIBLE_WITH: accountant, booking_beauty, booking_fitness, booking_medical, booking_restaurant, campaign_tracker, car_rental, course_tracker, debtors, event_manager, event_rsvp, expense_tracker, feedback_survey, manager_secretary, orders_tracker, repair_tracker, staff_scheduler, support_tickets, survey_form, tourist_documents, trip_manager, vehicle_service
"""Reusable Word (.docx) export feature — turns a flat set of field/value
answers (a completed questionnaire, a generated report) into a formatted
.docx document, in memory, for a host template to send to Telegram.

Same structural convention as features/sheets.py: no Config Protocol, no
init_db, no per-bot state of its own — every function takes the data to
export as plain arguments and returns bytes, never touching the database.
`router` is exported empty for the same by-convention reason sheets.py's is
(runtime/registry.py's _load_and_include_features() only warns and skips if
a feature module has no router — there is no Telegram-native event to hook
here, this is called programmatically from a host template's own handlers
after a questionnaire/report flow completes).

python-docx (requirements.txt) is a SYNCHRONOUS library doing in-memory
zip/XML work, not I/O — small enough (a handful of paragraphs/a table) that
it runs in well under a millisecond for realistic questionnaire sizes, so
unlike sheets.py's network calls this is NOT wrapped in asyncio.to_thread;
build_document() is a plain sync function and callers awaiting nothing is
correct. If a future caller ever builds documents large enough for this to
matter (many embedded images), wrap that specific call site in
asyncio.to_thread rather than making every caller pay for asyncio overhead
on the common case.
"""
from __future__ import annotations

import io
import logging
from datetime import datetime

from aiogram import Router
from docx import Document
from docx.shared import Pt

logger = logging.getLogger(__name__)

router = Router()

# Not enforced here — build_document() has no upload/send path of its own.
# For a future caller to check the returned bytes against before sending
# (Telegram's Bot API document limit is 50MB; this is the ТЗ's own tighter cap).
MAX_FILE_SIZE_BYTES = 20 * 1024 * 1024


def build_document(
    title: str,
    fields: list[tuple[str, str]],
    *,
    include_metadata: bool = True,
    bot_name: str | None = None,
    user_name: str | None = None,
) -> bytes:
    """Builds a .docx document with `title` as a heading and `fields` (an
    ordered list of (label, value) pairs — e.g. completed questionnaire
    answers) rendered as a two-column table. Returns the raw file bytes,
    ready to wrap in an aiogram BufferedInputFile.

    include_metadata=True (default) appends a small "generated by/for/at"
    footer paragraph — the export's provenance (which bot, which user, when)
    is often the only thing that lets an admin match a submitted document
    back to a chat, since python-docx has no access to Telegram identity."""
    document = Document()

    heading = document.add_heading(title, level=1)
    for run in heading.runs:
        run.font.size = Pt(18)

    if fields:
        table = document.add_table(rows=0, cols=2)
        table.style = "Light Grid Accent 1"
        for label, value in fields:
            row = table.add_row().cells
            row[0].text = str(label)
            row[1].text = str(value)

    if include_metadata:
        document.add_paragraph()
        meta_parts = [f"Сгенерировано: {datetime.now().strftime('%Y-%m-%d %H:%M')}"]
        if bot_name:
            meta_parts.append(f"Бот: {bot_name}")
        if user_name:
            meta_parts.append(f"Пользователь: {user_name}")
        meta_paragraph = document.add_paragraph(" · ".join(meta_parts))
        for run in meta_paragraph.runs:
            run.font.size = Pt(9)
            run.italic = True

    buffer = io.BytesIO()
    document.save(buffer)
    data = buffer.getvalue()
    logger.info(f"build_document: title={title!r} fields={len(fields)} size={len(data)} bytes")
    return data
